/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.higginson555.adam.gui;

import java.util.ArrayList;
import java.util.Properties;
 
import javax.mail.*;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam
 */
public class HomeScreen extends javax.swing.JFrame 
{
    
    //The amount of messages to show by default
    private static final int MESSAGES_DEFAULT_SIZE = 100;
    
    //Username and password for the user in this client
    private String username, password;
    //The properties to use for sending messages
    private Properties properties;
    //The properties for the config
    private Properties config;
    //An array list of every message 
    private ArrayList<Message> messages;
    //The store
    private Store store = null;
    //The inbox folder
    private Folder inbox = null;

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(String username, String password, Properties config) 
    {
        this.username = username;
        this.password = password;
        this.config = config;
        this.messages = new ArrayList<Message>(MESSAGES_DEFAULT_SIZE);
        
        String usernameProp = config.getProperty("username");
        String serverType = config.getProperty("server_type");
        String incoming = config.getProperty("incoming_server");
        
        System.out.println(incoming);
        //If these haven't been filled in, we can't connect to the server!
        if (usernameProp == null || serverType == null || incoming == null)
        {
            //Open up options pane
            OptionsScreen options = new OptionsScreen(config);
            options.setVisible(true);
            options.setAlwaysOnTop(true);
        }
        
        //Set properties
        //TODO At the moment this uses gmail stuff, perhaps enable customisation?

        this.properties = new Properties();
        properties.put("mail.smtp.host", "studentmail.cs.manchester.ac.uk");
        properties.put("mail.smtp.socketFactory.port", "465");
        properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.port", "465");

        
        //Initialise GUI
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Try connecting
        connectToServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emailList = new javax.swing.JList();
        composeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        settingsMenu = new javax.swing.JMenu();
        optionsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ultimate E-mail Client");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        emailList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        emailList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emailList);

        composeButton.setText("Compose");
        composeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                composeButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("E-mails");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTree1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        settingsMenu.setText("Settings");

        optionsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        optionsMenuItem.setText("Options");
        optionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(optionsMenuItem);

        jMenuBar1.add(settingsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(composeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(composeButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Activated when compose button is pressed. Creates a new ComposeMailScreen,
     * to allow the user to compose a new mail message
     */
    private void composeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composeButtonActionPerformed
        ComposeMailScreen mailScreen = 
           new ComposeMailScreen(this.username, this.password, this.properties);
        
        mailScreen.setVisible((true));
    }//GEN-LAST:event_composeButtonActionPerformed

    private void optionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsMenuItemActionPerformed
        OptionsScreen options = new OptionsScreen(config);
        options.setVisible(true);
    }//GEN-LAST:event_optionsMenuItemActionPerformed

    /*
     * Tries to connect to the server and opens a store
     */
    private void connectToServer()
    {
        try
        {
            Authenticator authenticator = new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
            };
            Session session = Session.getInstance(properties, authenticator);
            
            //config.load(new FileInputStream("config.properties"));
            
            //Read info from property file
            String usernameProp = config.getProperty("username");
            String serverType = config.getProperty("server_type");
            String incoming = config.getProperty("incoming_server");
            
            //If these haven't been filled in, we can't connect to the server!
            if (usernameProp == null || serverType == null || incoming == null)
            {
                JOptionPane.showMessageDialog(rootPane, "Make sure option fields are filled!", 
                                              "Error!", JOptionPane.OK_OPTION);
                
                return;
            }

            System.out.println("Username: " + usernameProp + " Server type: " + serverType + " incoming " + incoming);
            store = session.getStore(serverType.toLowerCase());
                
            
            //store = session.getStore(serverType);
            store.connect(incoming, usernameProp, this.password);
            
            //Get the default folder
            inbox = store.getDefaultFolder();
            if (inbox == null) 
                throw new Exception("No default inbox found!");
            inbox = inbox.getFolder("INBOX");
            if (inbox == null)
                throw new Exception("No inbox found!");
            inbox.open(Folder.READ_ONLY);
            
            //Get messages and add to messages array list
            int messageCount = inbox.getMessageCount();
            System.out.println("Getting: " + messageCount + " messages...");
            Message[] messagesArray = inbox.getMessages();
            System.out.println("Done!");
            
            System.out.println("Adding messages...");
            for (int i = 0; i < messagesArray.length; ++i)
            {
                messages.add(messagesArray[i]);
            }
            System.out.println("Done!");
            
            String[] messageTitle = new String[messagesArray.length];
            
            for (int i = 0; i < messagesArray.length; i++)
            {
                messageTitle[i] = messagesArray[i].getSubject();
            }
            
            System.out.println("Setting list data...");
            this.emailList.setListData(messageTitle);  
            System.out.println("Done!");
                
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }     
    }
    
    private void closeConnections() throws Exception
    {
        if (inbox != null) inbox.close(false);
        if (store != null) store.close();
    }
    
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        
        //First try and close existing connections
        try
        {
            closeConnections();
        }
        catch (Exception ex)
        {
            JOptionPane.showConfirmDialog(rootPane, "Error! Could not close connections!", "Error!", JOptionPane.OK_OPTION);
        }
        connectToServer();
    }//GEN-LAST:event_refreshButtonActionPerformed

    /*
     * If a double mouse click, we try to view the e-mail
     */
    private void emailListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailListMouseClicked
        
        JList list = (JList)evt.getSource();
        int index = -1;
        if (evt.getClickCount() == 2)
        {
            index = list.locationToIndex(evt.getPoint());
        }
        else if (evt.getClickCount() == 3) //triple click
        {
            index = list.locationToIndex(evt.getPoint());
        }
        
        if (index != -1)
        {
            Message selectedMessage = messages.get(index);
            ViewMailScreen viewMail = new ViewMailScreen(selectedMessage);
            viewMail.setVisible(true);
        }
    }//GEN-LAST:event_emailListMouseClicked

    @Override
    public void dispose()
    {
        try
        {
            closeConnections();
        }
        catch (Exception exClose) {exClose.printStackTrace();}
        
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               // new HomeScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton composeButton;
    private javax.swing.JList emailList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem optionsMenuItem;
    private javax.swing.JButton refreshButton;
    private javax.swing.JMenu settingsMenu;
    // End of variables declaration//GEN-END:variables
}
