/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.higginson555.adam.gui;

import com.gmail.higginson555.adam.MessageNode;
import com.gmail.higginson555.adam.StoreNode;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Properties;
import java.util.concurrent.CountDownLatch;
import java.util.logging.Level;
import java.util.logging.Logger;
 
import javax.mail.*;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Adam
 */
public class HomeScreen extends javax.swing.JFrame 
{
    
    //The amount of messages to show by default
    private static final int MESSAGES_DEFAULT_SIZE = 100;
    
    //Username and password for the user in this client
    private String username, password;
    //The properties to use for sending messages
    private Properties properties;
    //The properties for the config
    private Properties config;
    //An array list of every message 
    private ArrayList<Message> messages;
    //The store
    private Store store = null;
    //The inbox folder
    private Folder inbox = null;

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(String username, String password, Properties config) 
    {
        this.username = username;
        this.password = password;
        this.config = config;
        this.messages = new ArrayList<Message>(MESSAGES_DEFAULT_SIZE);
        
        //Initialise GUI
        initComponents();
        
        String usernameProp = config.getProperty("username");
        String serverType = config.getProperty("server_type");
        String incoming = config.getProperty("incoming_server");
        String outgoing = config.getProperty("outgoing_server");
        String smtpPort = config.getProperty("smtp_port");
        
        System.out.println(incoming);
        CountDownLatch countdown = null;
        //If these haven't been filled in, we can't connect to the server!
        if (usernameProp == null || serverType == null || incoming == null 
                || smtpPort == null || outgoing == null)
        {
            //Open up options pane
            countdown = new CountDownLatch(1);
            OptionsScreen options = new OptionsScreen(config, countdown);
            options.setVisible(true);
            options.setAlwaysOnTop(true);
        }
                       
        this.setLocationRelativeTo(null);
        
        //Try connecting, waiting for the options screen to exit if there is one
        if (countdown != null)
        {
            try 
            {
                System.out.println("AWAITING!");
                countdown.await();
            } catch (InterruptedException ex) 
            {
                JOptionPane.showMessageDialog(rootPane, ex.toString(), "Interrupted Exception!", JOptionPane.ERROR_MESSAGE);
            }
        }
        connectToServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        composeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        emailJTree = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        settingsMenu = new javax.swing.JMenu();
        optionsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ultimate E-mail Client");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("homeFrame");

        composeButton.setText("Compose");
        composeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                composeButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("E-mails");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        emailJTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailJTreeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(emailJTree);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        settingsMenu.setText("Settings");

        optionsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        optionsMenuItem.setText("Options");
        optionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(optionsMenuItem);

        jMenuBar1.add(settingsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(composeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 577, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(composeButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Activated when compose button is pressed. Creates a new ComposeMailScreen,
     * to allow the user to compose a new mail message
     */
    private void composeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composeButtonActionPerformed
        ComposeMailScreen mailScreen = 
           new ComposeMailScreen(this.username, this.password, this.properties);
        
        mailScreen.setVisible((true));
    }//GEN-LAST:event_composeButtonActionPerformed

    /*
     * TODO opening options
     */
    private void optionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsMenuItemActionPerformed
        
        //OptionsScreen options = new OptionsScreen(config);
        //options.setVisible(true);
    }//GEN-LAST:event_optionsMenuItemActionPerformed

    /*
     * Tries to connect to the server and opens a store
     */
    private void connectToServer()
    {
        try
        {
            Authenticator authenticator = new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
            };
            
            //Set properties
            this.properties = System.getProperties();
            this.properties.put("mail.smtp.auth", "true");
            this.properties.put("mail.smtp.starttls.enable", "true");
            this.properties.put("mail.smtp.host", config.getProperty("outgoing_server"));
            this.properties.put("mail.smtp.port", config.getProperty("smtp_port"));
            
            Session session = Session.getInstance(properties, authenticator);
            
            //config.load(new FileInputStream("config.properties"));
            
            //Read info from property file
            String usernameProp = config.getProperty("username");
            String serverType = config.getProperty("server_type");
            String incoming = config.getProperty("incoming_server");
            
            //If these haven't been filled in, we can't connect to the server!
            if (usernameProp == null || serverType == null || incoming == null)
            {
                JOptionPane.showMessageDialog(rootPane, "Make sure option fields are filled!", 
                                              "Error!", JOptionPane.OK_OPTION);
                
                return;
            }

            System.out.println("Username: " + usernameProp + " Server type: " + serverType + " incoming " + incoming);
            store = session.getStore(serverType.toLowerCase());
            
            buildJTree();
            
            //store = session.getStore(serverType);
            /*store.connect(incoming, usernameProp, this.password);
            
            //Get the default folder
            inbox = store.getDefaultFolder();
            if (inbox == null) 
                throw new Exception("No default inbox found!");
            inbox = inbox.getFolder("INBOX");
            if (inbox == null)
                throw new Exception("No inbox found!");
            inbox.open(Folder.READ_ONLY);
            
            //Get messages and add to messages array list
            int messageCount = inbox.getMessageCount();
            System.out.println("Getting: " + messageCount + " messages...");
            Message[] messagesArray = inbox.getMessages();
            System.out.println("Done!");
            
            System.out.println("Adding messages...");
            for (int i = 0; i < messagesArray.length; ++i)
            {
                messages.add(messagesArray[i]);
            }
            System.out.println("Done!");
            
            String[] messageTitle = new String[messagesArray.length];
            
            for (int i = 0; i < messagesArray.length; i++)
            {
                messageTitle[i] = messagesArray[i].getSubject();
            }
            
            System.out.println("Setting list data...");
            this.emailList.setListData(messageTitle);  
            System.out.println("Done!");*/
                
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }    
    }
    
    private void closeConnections() throws Exception
    {
        if (inbox != null) inbox.close(false);
        if (store != null) store.close();
    }
    
    //Attempts to build the tree, but only after the store object has been
    //built by connectToServer()
    private void buildJTree()
    {
        StoreNode storeNode = new StoreNode(store, config, password);        
        DefaultTreeModel treeModel = new DefaultTreeModel(storeNode);
        emailJTree.setModel(treeModel);
        emailJTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
        
    }
    
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        
        //First try and close existing connections
        try
        {
            closeConnections();
        }
        catch (Exception ex)
        {
            JOptionPane.showConfirmDialog(rootPane, "Error! Could not close connections!", "Error!", JOptionPane.OK_OPTION);
        }
        connectToServer();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void emailJTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailJTreeMouseClicked
        if (evt.getClickCount() == 2 || evt.getClickCount() == 3)
        {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode)emailJTree.getLastSelectedPathComponent();
        
            if (selectedNode instanceof MessageNode)
            {
                MessageNode messageNode = (MessageNode)selectedNode;
                ViewMailScreen viewMail = new ViewMailScreen(messageNode.getMessage());
                viewMail.setVisible(true);
            }
        }
    }//GEN-LAST:event_emailJTreeMouseClicked

    @Override
    public void dispose()
    {
        try
        {
            closeConnections();
        }
        catch (Exception exClose) {exClose.printStackTrace();}
        
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               // new HomeScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton composeButton;
    private javax.swing.JTree emailJTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem optionsMenuItem;
    private javax.swing.JButton refreshButton;
    private javax.swing.JMenu settingsMenu;
    // End of variables declaration//GEN-END:variables
}
